//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCP_Import.Models.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_OCP_ImportEntities : DbContext
    {
        public db_OCP_ImportEntities()
            : base("name=db_OCP_ImportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblSchedulerHistory> tblSchedulerHistories { get; set; }
        public virtual DbSet<tblSeller> tblSellers { get; set; }
        public virtual DbSet<tblSchedulerSetting> tblSchedulerSettings { get; set; }
    }
}
