//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCP_Import.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSeller()
        {
            this.tblSchedulerHistories = new HashSet<tblSchedulerHistory>();
            this.tblSchedulerSettings = new HashSet<tblSchedulerSetting>();
        }
    
        public int SellerId { get; set; }
        public string ShopifyAccessToken { get; set; }
        public string MyShopifyDomain { get; set; }
        public long ShopifyChargeId { get; set; }
        public string ShopName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string TimezoneOffset { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string InstallStatus { get; set; }
        public System.DateTime UnInstallDateTime { get; set; }
        public string ShopDomain { get; set; }
        public string Host { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchedulerHistory> tblSchedulerHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchedulerSetting> tblSchedulerSettings { get; set; }
    }
}
