//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OCP_Import.Models.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedulerSetting
    {
        public int SettingId { get; set; }
        public string FtpHost { get; set; }
        public string FtpUserName { get; set; }
        public string FtpPassword { get; set; }
        public string FtpPort { get; set; }
        public string FtpFilePath { get; set; }
        public string SyncTime { get; set; }
        public string Brand { get; set; }
        public int SellerId { get; set; }
        public System.DateTime UpdateAt { get; set; }
    
        public virtual tblSeller tblSeller { get; set; }
    }
}
